### ISSUE TITLE
docker-compose add sysctls for aio-max-nr

### ISSUE THREAD

**Issue by guy9** [scylladb/scylla-code-samples#207]
If a machine does not have the aio-max-nr value set correctly, starting the node fails. To solve this need to add to all docker-compose files in this repo, for each node:

....
```
 networks:
      web:
 sysctls:
      - fs.aio-max-nr=1048576
```

Currently, this fails as it is not supported by Docker. See here: https://docs.docker.com/engine/reference/commandline/run/#sysctl
Follow up on this, and once added by Docker, add it to our files.
