### ISSUE TITLE
Creating kubernetes statefulset doesnt work

### ISSUE THREAD

**Issue by ThePixelBro22** [scylladb/scylla-code-samples#22]
I wanna get Scylla on my GCP kubernetes and am following this guide.

https://github.com/scylladb/scylla-code-samples/tree/master/kubernetes-scylla

but when I run this command
`kubectl create -f scylla-statefulset.yaml`

I get an error

```
error: error validating "scylla-statefulset.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"apps", Version:"v1beta2", Kind:"StatefulSet"}; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by dorlaor** [comment]
@hakuch ^^

**Comment by hakuch** [comment]
At the time of writing this sample, StatefulSets were in beta.

According to the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) for StatefulSets, as of release 1.9 they are stable.

If you are running Kubernetes at release 1.9 or greater, I believe you can change `apiVersion` in `scylla-statefulset.yaml` to `apiVersion: 1`.

Does that resolve the error?

**Comment by ThePixelBro22** [comment]
@hakuch I am actually trying this on GKE which has a kube version of 1.8.6. So I changed the api version to 1 just for the fun of it and got

```
error: error validating "scylla-statefulset.yaml": error validating data: apiVersion isn't string type; if you choose to ignore these errors, turn validation off with --validate=false
```
And I'm not sure where to go from there. 
Also thank you so much for the help, I'm a big fan of your work and the keynotes you did helped a ton.

**Comment by hakuch** [comment]
@ThePixelBro22, I'm glad to help and appreciate your kind words.

I gave you incorrect advice: try `apiVersion: v1`.

If that doesn't work, I'll try to spin up a test cluster to try to figure this out definitively.

**Comment by ThePixelBro22** [comment]
@hakuch  
I get this error
```
error: error validating "scylla-statefulset.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"", Version:"v1", Kind:"StatefulSet"}; if you choose to ignore these errors, turn validation off with --validate=false
```
And this is  my yaml.

```
apiVersion: v1
kind: StatefulSet
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  serviceName: scylla
  replicas: 3
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:2.0.0
          imagePullPolicy: IfNotPresent
          args: ["--seeds", "scylla-0.scylla.default.svc.cluster.local"]
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "PID=$(pidof scylla) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - exec
                - /opt/ready-probe.sh
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: scylla-data
              mountPath: /var/lib/scylla
            - name: scylla-ready-probe
              mountPath: /opt/ready-probe.sh
              subPath: ready-probe.sh
      volumes:
        - name: scylla-ready-probe
          configMap:
            name: scylla
  volumeClaimTemplates:
    - metadata:
        name: scylla-data
        annotations:
          volume.beta.kubernetes.io/storage-class: scylla-ssd
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```
